[colors]
ansi = [
    "#141316",
    "#ffb4ab",
    "#eeb8cb",
    "#cac3dc",
    "#cbbeff",
    "#eeb8cb",
    "#cac3dc",
    "#e6e1e6",
]
background = "#141316"
brights = [
    "#938f99",
    "#ffb4ab",
    "#eeb8cb",
    "#cac3dc",
    "#cbbeff",
    "#eeb8cb",
    "#cac3dc",
    "#e6e1e6",
]
cursor_bg = "#e6e1e6"
cursor_border = "#e6e1e6"
cursor_fg = "#141316"
foreground = "#e6e1e6"
selection_bg = "#48454e"
selection_fg = "#cac4cf"

[metadata]
name = "Noctalia"
